name: deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: fountainhead/action-wait-for-check@v1.0.0
      name: Wait for code inspection
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        checkName: lint
      id: wait-for-inspect

    - uses: kanadgupta/glitch-sync@v1.0
      name: Sync repository to Glitch Application
      with:
        project-id: ${{ secrets.GLITCH_PROJECT_ID }}
        auth-token: ${{ secrets.GLITCH_AUTH_TOKEN }}
      if: steps.wait-for-inspect.outputs.conclusion == 'success'
